spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.166/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  jackson:
    default-property-inclusion: non_null
server:
  port: 80
  servlet:
    context-path: /sell

